# Generated by Django 5.1.6 on 2025-04-02 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_itemlocation_qty'),
        ('sale_orders', '0002_alter_saleorder_completed_alter_saleorder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_sale_order', to='locations.location'),
        ),
    ]
